services:
  - type: web
    name: attendance-tracker
    env: node
    region: oregon
    buildCommand: npm run build:frontend && cd backend && npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      NODE_VERSION: "20"
      NODE_ENV: "production"
